name: lecode_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  
  flutter:
    sdk: flutter
  # UI
  flutter_native_splash: ^2.2.8
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1
  fl_chart: ^0.55.2
  modal_bottom_sheet: ^2.1.2
  chips_choice: ^3.0.0
  msh_checkbox: ^1.2.1
  grouped_list: ^5.1.2
  easy_web_view: ^1.6.0
  
  
  # DI
  get_it: ^7.2.0
  injectable: ^1.5.3
  equatable: ^2.0.5

  # Misc
  meta: ^1.7.0
  rxdart: ^0.27.4
  json_annotation: ^4.7.0
  intl: ^0.17.0

  # Starter kit
  pocket:
    path: /Users/zoro/dev/flutter-projects/starter_kit_flutter/pocket
  drip:
    path: /Users/zoro/dev/flutter-projects/starter_kit_flutter/drip
  projectile:
    path: /Users/zoro/dev/flutter-projects/starter_kit_flutter/projectile

  # pocket:
  #   git:
  #     url: https://github.com/jamescardona11/starter_kit_flutter.git
  #     path: pocket/
      # ref: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

